### ISSUE TITLE
some other parameters

### ISSUE THREAD

**Issue by wwzz-max** [shaham-lab/SpectralNet#8]
Hello, can this method pass in some other parameters? Such as modifying the metric value, learning rate, number of epochs for learning, etc.

**Comment by AmitaiYacobi** [comment]
Hi!
Of course, you can pass all these parameters to the SpectralNet class.
after you'll install the package, you'll be able to see all possible parameters that can be passed to the SpectralNet class.
For example:
spectralnet = SpectralNet(
        n_clusters=2,
        spectral_batch_size=712,
        spectral_epochs=40,
        spectral_lr=1e-3
        spectral_hiddens=[128, 128, 2],
    )
and there are much more. Specifically for metrics, we only support ACC and NMI for now, and we compute them both in every running. But, you can change the code as you wish.
Let me know if there are another questions.
